services:
  - type: web
    name: black-panther-md
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node --max-old-space-size=512 index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        sync: false          # user sets this — must start with GURU~
      - key: BOT_NAME
        value: BLACK PANTHER MD
      - key: OWNER_NAME
        value: GuruTech
      - key: OWNER_NUMBER
        value: "254105521300"
      - key: BOT_PREFIX
        value: "."
      - key: MODE
        value: public
      - key: TIME_ZONE
        value: Africa/Nairobi
      - key: AUTO_BIO
        value: "true"
      - key: AUTO_LIKE_STATUS
        value: "true"
      - key: AUTO_READ_STATUS
        value: "true"
      - key: AUTO_REACT
        value: "false"
      - key: DEBUG
        value: "false"
